# pyproject.toml
[project]
name = "fp8-nvfp4-mps-metal" # Unique identifier for your node. Immutable after creation.
description = "Metal acceleration and compatibility patches for FP8 and NVFP4 ComfyUI models on Apple Silicon"
version = "0.1.0" # Custom Node version. Must be semantically versioned.
license = { file = "LICENSE.txt" }
dependencies  = [] # Filled in from requirements.txt

[project.urls]
Repository = "https://github.com/akblissweb/fp8-nvfp4-mps-metal"

[tool.comfy]
PublisherId = "akblissweb" # TODO (confirm Publisher ID from Comfy Registry Website before publishing).
DisplayName = "fp8-nvfp4-mps-metal" # Display name for the Custom Node. Can be changed later.
Icon = "https://avatars.githubusercontent.com/u/248655186?s=400&u=c76a1b563147e1765aa43ec50daa33d3397ad222&v=4" # SVG, PNG, JPG or GIF (MAX. 800x400px)
